name: CI Build

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x ]    
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm t
      - run: npm run build
      - run: npm run build:browser
      - run: npm run docs
      - name: Publish generated docs to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          dir: docs
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
